### ISSUE TITLE
Disable embedding/crawling on URLs

### ISSUE THREAD

**Issue by burritosoftware** [discord-relay-chat/drc#28]
This would be a configurable option that encases all URLs being received in Discord with <> characters to prevent embedding/crawling of the URL by Discord's bot, for privacy.

**Comment by edfletcher** [comment]
This is a great idea! Will definitely add this 👍

**Comment by CovertDuck** [comment]
Correct me if I’m wrong, but I believe that the generated URL previews are done via a Discord server and then served to the Discord client. So, receiving a link/embed message doesn’t compromise the user.

But that could change. Adding the brackets offers an additional layer of security, I'm all for it.

**Comment by edfletcher** [comment]
Resolved by https://github.com/discord-relay-chat/drc/commit/aeda423ba00bfb7da82774523c51c35d1a198881

The new setting is `config.discord.disableUrlEmbeds` and it defaults to `true`.

Enjoy, and thank you again for the idea @burritosoftware and the feedback @CovertDuck!
